### ISSUE TITLE
failed to get provider configuration from discovery in docker-compose

### ISSUE THREAD

**Issue by TcaManager** [bitnami/bitnami-docker-keycloak-gatekeeper#11]
**Description**

**Steps to reproduce the issue:**

1. Configuration

I have the following docker-compose file

```yml
version: '3.2'

services:
  postgres:
    image: postgres
    volumes:
      - type: bind
        source: ../postgres_data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pa55w0rd
    ports:
      - 5432:5432
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'Pa55w0rd'
    volumes:
      - type: bind
        source: ../pgadmin_data
        target: /var/lib/pagadmin
    ports:
      - 5050:80
    restart: unless-stopped
    depends_on:
      - postgres
  ldap:
    image: i2hm/openldap:latest
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: Pa55w0rd
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - postgres
  gatekeeper:
    image: bitnami/keycloak-gatekeeper:latest
    command: /keycloak-gatekeeper --config /opt/bitnami/keycloak-gatekeeper/config.yaml
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ../gatekeeper/config.yaml
        target: /opt/bitnami/keycloak-gatekeeper/config.yaml
    depends_on:
      - keycloak
      - web
  web:
    build: .
    volumes:
      - type: bind
        source: ../gunicorn_log
        target: /var/log
    ports:
      - 5000:5000
    depends_on:
      - postgres
```

And the following config.yaml file for Gatekeeper

```yaml
client-id: flask_example
client-secret: 7216c35c-0f0a-4dbf-adc8-beb0dc933f27
discovery-url: http://keycloak:8080/auth/realms/identite
enable-default-deny: true
listen: :3000
upstream-url: http://localhost:5000
resources:
- uri: /admin*
  methods:
  - GET
  roles:
  - client:test1
  - client:test2
  require-any-role: true
  groups:
  - admins
  - users
- uri: /backend*
  roles:
  - client:test1
- uri: /public/*
  white-listed: true
- uri: /favicon
  white-listed: true
- uri: /css/*
  white-listed: true
- uri: /img/*
  white-listed: true
headers:
  myheader1: value_1
  myheader2: value_2
```

2. Unexpected result

When I run this command

```bash
docker-compose up
```

I get the following error.

```bash
gatekeeper_1  | 1.5979106087258694e+09	info	attempting to retrieve configuration discovery url	{"url": "http://keycloak:8080/auth/realms/identite", "timeout": "30s"}
gatekeeper_1  | 1.597910608726886e+09	warn	failed to get provider configuration from discovery	{"error": "Get \"http://keycloak:8080/auth/realms/identite/.well-known/openid-configuration\": dial tcp 172.24.0.6:8080: connect: connection refused"}
```

If I replace keycloak with localhost, I get a similar error, though on my browser, http://keycloak:8080/auth/realms/identite/.well-known/openid-configuration URL is reachable and gives the expected JSON response.

I wonder if this can be related to this issue https://github.com/louketo/louketo-proxy/issues/576

Thanks for your help.
