### ISSUE TITLE
Container fails to start

### ISSUE THREAD

**Issue by huegelc** [bitnami/bitnami-docker-keycloak-gatekeeper#3]
Hi,
It seems that the configuration file is ignored during the container startup:
```
Attaching to gatekeeper_keycloak-gatekeeper_1
keycloak-gatekeeper_1  | [error] you have not specified the listening interface
gatekeeper_keycloak-gatekeeper_1 exited with code 1
```
```
discovery-url: http://keycloak.lan/auth/realms/sso
client-id: example
client-secret: f3asdc-78b2-4601-b4f8-961f2af5a331
listen: 0.0.0.0:3001
enable-refresh-tokens: false
redirection-url: http://example.lan
encryption-key: Agasddasdd(/"JZDSH4X0XhL5Qy2Z2j
upstream-url: http://127.0.0.1:4181
enable-token-header: false
enable-authorization-cookies: false
enable-refresh-tokens: true
enable-login-handler: true
http-only-cookie: true
cookie-access-name: sso-xxxxxx
cookie-refresh-name: sso-yyyyyy
preserve-host: true
scopes:
  - offline_access
match-claims:
  aud: metropolis
  iss: http://keycloak.lan/auth/realms/sso
add-claims:
  - name
resources:
  - uri: /*
    roles:
      - offline_access
    groups:
      - admin
```

**Comment by juan131** [comment]
Hi @huegelc 

How are you mounting the configuration file? Are you following the instructions below?

- [Using a configuration file](https://github.com/bitnami/bitnami-docker-keycloak-gatekeeper#using-a-configuration-file)

Could you share the commands/docker-compose you're using to deploy this container?

**Comment by huegelc** [comment]
Hi @juan131 ,

yes, I'm mounting it via dockerfile
```
version: '2'

services:
  keycloak-gatekeeper:
    image: bitnami/keycloak-gatekeeper:latest
    ports:
      - '3001:3001'
    volumes:
      - /root/gatekeeper/config.yaml:/opt/bitnami/keycloak-gatekeeper/config.yaml/config.yaml
```

config:
```
discovery-url: http://nas-10-keycloak.lan/auth/realms/sso
client-id: metropolis
client-secret: f3c1faac-78b2-4601-b4f8-961f2af5a331
listen: 127.0.0.1:3001
enable-refresh-tokens: false
redirection-url: http://nas-10-metropolis.lan
encryption-key: Agasd0ZDS#######L5Qy2Z2j
upstream-url: http://127.0.0.1:4181
enable-token-header: false
enable-authorization-cookies: false
enable-refresh-tokens: true
enable-login-handler: true
http-only-cookie: true
cookie-access-name: sso-xxxxxx
cookie-refresh-name: sso-yyyyyy
preserve-host: true
scopes:
  - offline_access
match-claims:
  aud: metropolis
  iss: http://nas-10-keycloak.lan/auth/realms/sso
add-claims:
  - name
resources:
  - uri: /*
    roles:
      - offline_access
    groups:
      - admin
```

**Comment by juan131** [comment]
The problem is that you're not indicating the `--config ` flag to the `keycloak-proxy` command. Please try with the Docker Compose below:

```
version: '2'

services:
  keycloak-gatekeeper:
    image: bitnami/keycloak-gatekeeper:latest
    ports:
      - '3001:3001'
    command: /keycloak-proxy --config /opt/bitnami/keycloak-gatekeeper/config.yaml
    volumes:
      - ./config.yaml:/opt/bitnami/keycloak-gatekeeper/config.yaml:ro
```
